### ISSUE TITLE
July data updates

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-layers-api#193]
**Need to update:**
- [ ] DCM files - currently available (Note: this is the first update of the new DCM data. There may be unexpected issues, so we should check the app carefully afterward)
- [ ] Monthly zoning files - currently available
- [ ] MapPluto - once EDM confirms final content (~July 22)

**Tasks:**
- [ ] Update CSV
- [ ] Run python script
- [ ] Check results on apps
